version: "3.9"

services:
  dg-content-control:
    image: assafushy/dg-content-control:latest
    ports:
      - "3000:3000"
  dg-api-gate:
    image: assafushy/dg-api-gate:latest
    ports:
      - "3001:3000"
    environment:
      dgContentControlUrl: "http://dg-content-control:3000"
      jsonToWordPostUrl: "http://json-to-word:5000"
  json-to-word:
    image: assafushy/json-to-word:latest
    ports:
      - "5000:5000"
    environment:
      MinioUrl: "http://s3:9000"
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "4000:4000"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: "your-key"
      MINIO_SECRET_KEY: "your-secret"
      MINIO_ROOT_USER: "your-root-user"
      MINIO_ROOT_PASSWORD: "your-root-password"
      MINIO_REGION: "ap-southeast-1"
    command: server --address 0.0.0.0:9000  --console-address ":4000" /data
